project: 
  type: website
  output-dir: docs

execute: 
  freeze: auto

website: 
  title: "ASU-GO"
  favicon: favicon.png
  navbar: 
    left: 
      - text: Protocols
        href: protocols.md
      - text: Useful links
        href: links.md
      - text: About
        href: about.md

  sidebar:
    - title: "xProtocols"
      style: docked
      search: true
      contents: protocol-*.md

  page-footer: 
    left: 
      Made using Quarto
    right: 
      - icon: github
        href: https://github.com/hamdybakry/asugo
      - Curated by HB; Â© Ain Shams University 2025

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true
    
